use_frameworks!

platform :ios, '9.0'

target 'ZZUIKit_Example' do
  pod 'ZZUIKit', :path => '../'
  pod 'Masonry', '~> 1.1.0'
#  pod 'ZZFoundation',:path => '/Users/max/Desktop/github/ZZLib/ZZFoundation'
  pod 'DoraemonKit', '~> 3.0.6'
  
  target 'ZZUIKit_Tests' do
    inherit! :search_paths
    pod 'Kiwi'
    pod 'FBSnapshotTestCase'  
  end
end
